namespace ManchkinCore;

public enum DisposableStuff
{
    GETTING_LEVEL,
    STEALING_LEVEL,
    
    COOLNESS_POTION,
    FRIENDSHIP_POTION,
    DORMANT_POTION,
    SWITCHMAN_POTION,
    CONFUSION_POTION,
    INVISIBILITY_POTION,
    COLD_POTION,
    ELECTRIC_POTION,
    STINK_POTION,
    FIRE_POTION,
    HALFMORPH_POTION,
    COURAGE_POTION,

    OLD_MONSTER,
    STRAY_MONSTER,
    SMALL_MONSTER,
    HUGE_MONSTER,
    ANGRY_MONSTER,
    SMART_MONSTER,
    
    UGLY_TWINS,
    
    DIVINE_INTERVENTION,
    KILLING_MERCENARY,
    SENDING_BACK,
    BALLOONS,
    ELVEN_DRINK,
    TREASURE,
    MAGIC_ROCKET,
    DOWSER_PIN,
    RING,
    MAGIC_LAMP,
    WALL,
    DOPPELGANGER,
    GLUE,
    PROTEIN,
    MOCKERY_OF_CORPSES,
    CHEATER_CUBE,
    OBSESSION,
    SIDE_HELP,
}