namespace ManchkinCore.Enums;

public enum Curses
{
    LOST_LEVEL,
    LOST_HUGE_STUFF,
    LOST_SMALL_STUFF,
    LOST_DONNED_ARMOR,
    LOST_DONNED_SHUES,
    LOST_DONNED_HAT,
    LOST_CLASS,
    LOST_RACE,
    LOST_TWO_CARDS,
    
    CHANGE_CLASS,
    CHANGE_GENDER,
    CHANGE_RACE,
    
    CHICKEN_CURSE,
    CURRUPTED_MIRROR,
    FATAL_DIVE,
    VILE_CURSE,
    INCOME_TAX,
}